services:
  app:
    image: node:18
    volumes:
      - .:/app
    working_dir: /app
    command: bash
    tty: true
    stdin_open: true
    environment:
      - PORT=3009
    ports:
      - 3009:3009
